import assert from 'node:assert/strict';
import {PhotoBlobCache} from '../mockup-ui/photo-cache.js';
const revoked=[],created=[];
const urls={createObjectURL:()=>{const url=`blob:${created.length}`;created.push(url);return url;},revokeObjectURL:url=>revoked.push(url)};
let requests=0;
const cache=new PhotoBlobCache({bytes:8,entries:2,urls,fetcher:async()=>{requests++;return {ok:true,blob:async()=>new Blob(['1234'],{type:'image/png'})};}});
const first=await cache.acquire('a','/a');first.release();
const repeat=await cache.acquire('a','/a');assert.equal(requests,1);assert.equal(first.url,repeat.url);
const second=await cache.acquire('b','/b');second.release();
const third=await cache.acquire('c','/c');third.release();
assert.deepEqual(revoked,[second.url]);assert.equal(cache.bytes,8);
await assert.rejects(cache.acquire('huge','/huge',{signal:AbortSignal.abort()}),{name:'AbortError'});
repeat.release();cache.clear();assert.equal(cache.bytes,0);assert.equal(revoked.length,3);
let release;
const concurrent=new PhotoBlobCache({urls,fetcher:async()=>{await new Promise(resolve=>release=resolve);return {ok:true,blob:async()=>new Blob(['a'],{type:'image/jpeg'})};}});
const controller=new AbortController();
const canceled=concurrent.acquire('x','/x',{signal:controller.signal});
const alive=concurrent.acquire('x','/x');
controller.abort();await assert.rejects(canceled,{name:'AbortError'});release();
const leased=await alive;assert.ok(leased.url);leased.release();concurrent.clear();
let clearedRelease;
const cleared=new PhotoBlobCache({urls,fetcher:async()=>{await new Promise(resolve=>clearedRelease=resolve);return {ok:true,blob:async()=>new Blob(['a'],{type:'image/png'})};}});
const pending=cleared.acquire('secret','/x');cleared.clear();clearedRelease();
await assert.rejects(pending,{name:'AbortError'});assert.equal(cleared.items.size,0);
console.log('PASS: bounded Photos blob LRU, mounted leases, coalescing, cancellation and session clear');

const bounded=new PhotoBlobCache({urls,fetcher:async()=>({ok:false,status:413})});
await assert.rejects(bounded.acquire('oversized','/thumb'), /Preview exceeds server limits/);
